services:
  postgres:
    container_name: DStudio-db
    image: postgres:17 # It's better to specify a version like postgres current version
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: Dstudio
      POSTGRES_PASSWORD: ${DOCKER_PASSWORD}

volumes:
  postgres_data:
